exclude:
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"
  - "node_modules"
  - "package.json"
  - "package-lock.json"
  - "postcss.*.js"
  - "svg"
  - "svg-sprite.config.json"
  - "vendor"
  - "docker-compose.yml"
  - "renovate.json"
  - "css"
  - "js"

include:
  - "dist"
