version: '3'

services:

  jekyll:
    container_name: bic-jekyll

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - $PWD/:/jekyll
      - /jekyll/node_modules

    working_dir: /jekyll

    environment:
      NODE_ENV: development
      JEKYLL_ENV: development

    ports:
      - '4000:4000'
      - '5005:5005'

    #command: sh -c "npm start"
    command: npm start
