services:

  bic-jekyll:
    container_name: bic-jekyll
    image: bretfisher/jekyll-serve

    command: bundle exec jekyll serve --watch --livereload --force_polling

    volumes:
      - .:/site

    restart: unless-stopped

    environment:
      JEKYLL_ENV: development

    ports:
      - '5005:5005'
