services:
  bic-jekyll:
    container_name: bic-jekyll
    image: bretfisher/jekyll-serve

    volumes:
      - .:/site

    restart: unless-stopped

    environment:
      JEKYLL_ENV: development

    ports:
      - "5005:5005"
      - "35729:35729"

    command: bundle exec jekyll serve --watch --livereload --force_polling
