name: Deploy to dev

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install Node packages
        run: npm ci --production

      - name: Build assets
        run: npm run build

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Jekyll build
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --config "_config.yml,_config.prod.yml"
          printf "User-agent: *\nDisallow: /" > _site/robots.txt
          echo dev.beautyincode.se > _site/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: LivingIT/dev.beautyincode.se
          publish_branch: gh-pages
          publish_dir: _site

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: '*Deploy to https://dev.beautyincode.se*'
          mention: 'here'
          mention_if: 'failure'
          channel: '#beautyincode-site'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
