name: Deploy to dev 🚀

on:
  push:
    branches:
      - develop

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'

      - name: Install Node packages
        run: yarn install --production --pure-lockfile --non-interactive

      - name: Build assets
        run: yarn run build

      - name: Set up Ruby 2.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4.x

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Jekyll build
        env:
          JEKYLL_ENV: production
        run: jekyll build --config "_config.yml,_config.prod.yml"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2.10.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: LivingIT/dev.beautyincode.se
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: _site

      # - name: Slack Notification
      #   uses: homoluctus/slatify@master
      #   if: always()
      #   with:
      #     type: ${{ job.status }}
      #     job_name: '*Deploy to https://dev.beautyincode.se*'
      #     channel: '#beautyincode-site'
      #     url: ${{ secrets.SLACK_WEBHOOK }}
      #     commit: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
