name: Github Actions bot test 🤖

on: [push]

jobs:
  bot:

    name: Test Github Actions bot

    runs-on: ubuntu-18.04

    steps:
      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Lint Check*'
          mention: 'here'
          mention_if: 'failure'
          channel: '#github-actions-test'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
